#??????
server:
  port: 8899
#?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fis?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# mybatis????
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.briup.fis.bean
#mybatis??sql
logging:
  level:
    com.briup.fis.dao: debug
